routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Cargas routes
 */
require('routes/routes.cargas.php');



/**
 * Service request public routes
 */
Route::get('/request', 'AppointmentsController@getServiceRequest');
Route::post('/request', 'AppointmentsController@postServiceRequest');
Route::post('/request/verify-phone', 'AppointmentsController@verifyPhone');

/*
 * Contracts public routes - these are the old contract routes
 */
//Route::get('contracts/{id}/sign/{hash}', 'ContractsController@signContractLink')->name('contracts.sign');
//Route::get('contracts/{id}/download/{hash}', 'ContractsController@downloadContractLink');
//Route::put('contracts/sign/email/client', 'ContractsController@signEmailClient');
//Route::get('contracts/thankyou', function() {
//	return view('contracts.thankyou');
//})->name('contracts.thankyou');

/*
 * Agreements public routes
 */
Route::get('agreements/{id}/sign/{hash}', 'AgreementsController@signAgreementLink')->name('agreements.sign');
Route::get('agreements/{id}/download/{hash}', 'AgreementsController@downloadAgreementLink');
Route::put('agreements/sign/email/client', 'AgreementsController@signEmailClient');
Route::get('agreements/thankyou', function() {
    return view('agreements.thankyou');
})->name('agreements.thankyou');

/*
 * User routes
 */
Route::middleware(['user'])->group(function () {
	Route::get('/', 'HomeController@index');
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::get('estimates/active', 'EstimatesController@active')->name('estimates.active');
    Route::get('estimates/expired', 'EstimatesController@expired')->name('estimates.expired');
	Route::resource('estimates', 'EstimatesController');
    Route::patch('/estimates/update/column/{item}', 'EstimatesController@updateByColumn');
    Route::get('estimates/{id}/pdf', 'EstimatesController@generatePdf');
    Route::post('estimates/email', 'EstimatesController@sendEstimatePDFByEmail');

    // Agreements
    Route::get('agreements', 'AgreementsController@index')->name('agreements.index');
    Route::get('agreements/create/{base?}', 'AgreementsController@create')->name('agreements.create');
    Route::post('agreements/initiate', 'AgreementsController@initiate')->name('agreements.initiate');
    Route::get('agreements/prepare', 'AgreementsController@prepare')->name('agreements.getPrepare');
    Route::post('agreements/prepare', 'AgreementsController@prepare')->name('agreements.prepare');
    Route::post('agreements/services', 'AgreementsController@services')->name('agreements.services');
    Route::get('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/filled/client', 'AgreementsController@showFilledAgreementToClient')->name('agreements.show.client');
    Route::get('agreements/filled/employee', 'AgreementsController@showFilledAgreementToEmployee')->name('agreements.show.employee');
    Route::post('agreements/sign/client', 'AgreementsController@signNowClient');
    Route::post('agreements/sign/employee', 'AgreementsController@signNowEmployee');
    Route::get('agreements/store', 'AgreementsController@store');
    Route::get('agreements/{id}/download', 'AgreementsController@downloadAgreementPDF');
    Route::post('agreements/sign/email', 'AgreementsController@sendAgreementViaEmail');
    Route::post('agreements/resend', 'AgreementsController@resendAgreementLink');
    Route::put('agreements/sign/email/employee', 'AgreementsController@signEmailEmployee');
    Route::get('agreements/pending', 'AgreementsController@getPendingAgreements')->name('agreements.pending');
    Route::get('agreements/signed', 'AgreementsController@getSignedAgreements')->name('agreements.signed');
    Route::get('agreements/{agreement}/', 'AgreementsController@show');
    Route::delete('agreements/{agreement}', 'AgreementsController@destroy');

    // Create contract from estimates, contacts, addresses and leads
    // These are the old routes for contracts.
//	Route::get('estimates/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('estimates.create.contract');
//	Route::get('contacts/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('contacts.create.contract');
//	Route::get('addresses/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('addresses.create.contract');
//	Route::get('leads/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('leads.create.contract');

//  Route::resource('contracts', 'ContractsController')->only(['index']);
//  Route::post('contracts/services', 'ContractsController@configureServices');
//  Route::post('contracts/filled/client', 'ContractsController@showFilledContractToClient');
//  Route::post('contracts/sign/client', 'ContractsController@signNowClient');
//  Route::get('contracts/filled/employee', 'ContractsController@showFilledContractToEmployee');
//  Route::post('contracts/sign/employee', 'ContractsController@signNowEmployee');
//  Route::get('contracts/store', 'ContractsController@store');
//  Route::get('contracts/{id}/download', 'ContractsController@downloadContractPDF');
//	Route::post('contracts/sign/email', 'ContractsController@sendContractViaEmail');
//	Route::post('contracts/resend', 'ContractsController@resendContractLink');
//  Route::put('contracts/sign/email/employee', 'ContractsController@signEmailEmployee');
//  Route::get('contracts/pending', 'ContractsController@getPendingContracts')->name('contracts.pending');
//  Route::get('contracts/signed', 'ContractsController@getSignedContracts')->name('contracts.signed');
//	Route::get('contracts/migrate', 'ContractsController@migrate')->name('contracts.migrate');
//	Route::get('contracts/{contract}/', 'ContractsController@show');
//	Route::delete('contracts/{contract}', 'ContractsController@destroy');

    Route::resource('lineitems', 'EstimateItemsController');
    Route::patch('/lineitems/update/column/{item}', 'EstimateItemsController@updateByColumn');

    Route::resource('jobitems', 'JobItemsController');

    Route::resource('contacts', 'ContactsController');
    Route::get('/contacts/search/{query}', 'ContactsController@search');

    Route::resource('addresses', 'AddressesController');
    Route::get('/addresses/search/{string}', 'AddressesController@search');

	Route::resource('users', 'UsersController');
	Route::post('/users/{user}/avatar', 'UsersController@updateAvatar');
	Route::post('/users/{user}/change-password', 'UsersController@changePassword');
	Route::get('/users/search/{string}', 'UsersController@search');
	Route::post('/users/roles', 'UsersController@roles')->name('users.roles');
	Route::post('/users/{user}/signature', 'SignaturesController@store')->name('users.signature');
	Route::patch('/users/{user}/signature', 'SignaturesController@update');
	Route::delete('/users/{user}/signature', 'SignaturesController@destroy');
	Route::get('/users/{user}/unread-notifications', 'UsersController@getAllUnreadNotifications');
	Route::post('/users/{user}/read-notification', 'UsersController@markNotificationAsRead');
	Route::post('/users/{user}/read-all-notifications', 'UsersController@markAllNotificationsAsRead');
	Route::post('/users/{user}/send-message', 'MessagesController@send');
	Route::post('/users/send-message', 'MessagesController@send');
	Route::get('/messages/{message}', 'MessagesController@show');
	Route::delete('/messages/{message}', 'MessagesController@destroy');
	Route::patch('/messages/{message}/mark-as-read', 'MessagesController@markMessageAsRead');

	Route::resource('roles', 'RolesController');
	Route::resource('permissions', 'PermissionsController');

	Route::resource('appointments', 'AppointmentsController');
	Route::get('requests', 'AppointmentsController@getAllServiceRequests')->name('appointments.requests');
	Route::post('appointments/{appointment}/calendar-invite', 'AppointmentsController@calendarInvite');

	Route::resource('leads', 'LeadsController');
	Route::post('leads/{lead}/add-activity', 'LeadsController@addActivity');
	Route::post('leads/{lead}/assign/{user}', 'LeadsController@assign');

	Route::resource('notes', 'NotesController');

	Route::get('tickets/tanks', 'TicketsController@getTanks');
	Route::get('tickets/open', 'TicketsController@getOpenTickets')->name('tickets.open');
	Route::get('tickets/submitted', 'TicketsController@getSubmittedTickets')->name('tickets.submitted');
	Route::get('tickets/cleared', 'TicketsController@getClearedTickets')->name('tickets.cleared');
	Route::get('tickets/closed', 'TicketsController@getClosedTickets')->name('tickets.closed');
	Route::get('tickets/get-customer-types', 'TicketsController@getCustomerTypes');
	Route::resource('tickets', 'TicketsController');
	Route::post('tickets/add', 'TicketsController@addTicket');
	Route::patch('tickets/{ticket}/add-items', 'TicketsController@addItems');
	Route::patch('tickets/{ticket}/change-status', 'TicketsController@changeStatus');
	Route::get('tickets/{ticket}/get-ticket-activity', 'TicketsController@getTicketActivity');

	Route::get('search', 'SearchController@search');

	Route::post('shared/directories', 'AttachmentsController@directories');
	Route::post('shared/files', 'AttachmentsController@files');
});

/*
 * Admin routes
 */
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
	Route::get('/emails/logs', 'EmailLogsController@index')->name('emails.logs');
	Route::delete('/emails/logs/{log}', 'EmailLogsController@destroy');
	Route::get('/filemanager', function() {
		return view('filemanager.index');
	})->name('filemanager.index');
});

Auth::routes();

/*
 * API Requests
 */

app/Http/Controllers/LeadsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LeadsFormRequest;
use App\Lead;
use App\LeadActivity;
use App\Tag;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class LeadsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request, Lead $lead)
    {
        $leads = $lead->newQuery();

        if($request->has('bucket')) {
            if($request->bucket == '0') {
                $leads->where('bucket', '>', 0);
            } else {
                $leads->where('bucket', $request->bucket);
            }
        }

        if($request->has('assignee')) {
            if($request->assignee != 0) {
                $leads->whereHas('assignees', function ($query) use ($request) {
                    $query->where('lead_user.user_id', $request->assignee);
                });
            }
        }

        if($request->has('sort_by')) {
            if($request->sort_by == 'name') {
                $leads->select('leads.*')
                    ->leftJoin('contacts', 'leads.contact_id', '=', 'contacts.id')
                    ->orderBy('contacts.last_name', $request->sort_order);
            } else {
                $leads->orderBy($request->sort_by, $request->sort_order);
            }

        }

        $leads = $leads->latest()->get();
        $buckets = config('leads.buckets');
        $users = User::all();

        return view('leads.list', [
            'leads' => $leads,
            'buckets' => $buckets,
            'users' => $users,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param Lead $lead
     * @return \Illuminate\View\View
     */
    public function show(Lead $lead)
    {
        $activities = $lead->activities;

        foreach ($activities as $activity) {
            if(Carbon::now()->startOfDay()->equalTo(Carbon::parse($activity->date))) {
                $activity->class_name = 'due-today';
            } else if(Carbon::now()->startOfDay()->greaterThan(Carbon::parse($activity->date))) {
                $activity->class_name = 'expired';
            }
        }

        return view('leads.show', compact('lead'));
    }

    /**
     * Show the form for creating a new resource
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('create_contacts');

        return view('leads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param LeadsFormRequest $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(LeadsFormRequest $request)
    {
        $this->authorize('create_contacts');

        $tags = [];

        if(!empty($request->tags)) {
            $tags = explode(',', $request->tags);

            foreach ($tags as $key => $tag) {
                $tags[$key] = ucwords($tag);
            }
        }

        $lead = Lead::create([
            'address_id' => $request->address_id,
            'contact_id' => $request->contact_id,
            'bucket' => $request->bucket,
            'priority' => $request->priority,
            'lead_notes' => $request->lead_notes,
            'tags' => $tags,
        ]);

        return redirect($lead->path())
            ->with('flash', 'A new lead has been created!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Lead $lead
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Lead $lead)
    {
        return view('leads.edit', compact('lead'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Lead $lead
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Lead $lead, Request $request)
    {
        $buckets = config('leads.buckets');
        $priorities = config('leads.priorities');

        if(!array_key_exists($request->priority, $priorities)) {
            $request->offsetUnset('priority');
        }

        if(!array_key_exists($request->bucket, $buckets)) {
            $request->offsetUnset('bucket');
        }

        $request->validate([
            'bucket' => 'required',
            'priority' => 'required',
        ]);

        $tags = [];

        if(!empty($request->tags)) {
            $tags = explode(',', $request->tags);

            foreach ($tags as $key => $tag) {
                $tags[$key] = ucwords($tag);
            }
        }

        $lead->update([
            'bucket' => $request->bucket,
            'priority' => $request->priority,
            'lead_notes' => $request->lead_notes,
            'tags' => $tags
        ]);

        return redirect($lead->path())->with('flash', 'The lead has been updated!');
    }

    /**
     * Add a lead activity.
     *
     * @param Lead $lead
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function addActivity(Lead $lead, Request $request)
    {
        $request->validate([
            'type' => 'required',
            'bucket' => 'required',
            'date' => 'required',
            'time' => 'required',
            'notes' => 'required'
        ]);

        $activity = LeadActivity::create([
            'user_id' => auth()->id(),
            'lead_id' => $lead->id,
            'type' => $request->type,
            'bucket' => $request->bucket,
            'date' => date('Y-m-d', strtotime($request->date)),
            'time' => $request->time,
            'notes' => $request->notes,
        ]);

        if($request->change_bucket) {
            $activity->lead()->update([
                'bucket' => $request->bucket,
            ]);
        }

        return response()->json([
            'message' => 'A new activity was added',
            'redirect' => $lead->path(),
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Lead $lead
     * @return array
     * @throws \Exception
     */
    public function destroy(Lead $lead)
    {
        $lead->delete();

        return [
            'redirect' => route('leads.index'),
            'message' => 'Your Lead was deleted!'
        ];
    }

    /**
     * Assign lead to user.
     *
     * @param Lead $lead
     * @param User $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function assign(Lead $lead, User $user)
    {
        try {
            $user->assignLeads([$lead->id]);
        } catch (\Exception $e) {
            abort(422, 'Something went wrong');
        }

        return response()->json([
            'message' => 'The lead was assigned to ' . $user->name,
            'redirect' => route('leads.index'),
        ], 200);
    }
}

resources/views/leads/create.blade.php
@extends('template.main')

@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Add Lead</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Form</h2>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <form id="contact-form" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{{ route('leads.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Address <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <autocomplete-address></autocomplete-address>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Bucket <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select id="bucket" name="bucket" required="required" class="form-control col-md-7 col-xs-12">
                                        @foreach(config('leads.buckets') as $key => $bucket)
                                            <option value="{{ $key }}">{{ $bucket }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="priority">
                                    Priority <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select id="priority" name="priority" required="required" class="form-control col-md-7 col-xs-12">
                                        @foreach(config('leads.priorities') as $key => $priority)
                                            <option value="{{ $key }}">{{ $priority }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tags</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <autocomplete-tags></autocomplete-tags>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="priority">Note</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea class="form-control" name="lead_notes" cols="30" rows="5"></textarea>
                                </div>
                            </div>

                            <div class="ln_solid"></div>

                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-primary" type="reset">Reset</button>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/leads/edit.blade.php
@extends('template.main')

@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Update Lead</h3>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Form</h2>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <form id="contact-form" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{{ $lead->path() }}">
                            {!! method_field('patch') !!}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Contact name
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control" disabled value="{{ $lead->contact->fullName }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Company name
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control" disabled value="{{ $lead->contact->company }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Phone number
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control" disabled value="{{ $lead->contact->phone }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Email
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control" disabled value="{{ $lead->contact->email }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Address
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" class="form-control" disabled value="{{ $lead->address->fullAddress }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                    Bucket <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select id="bucket" name="bucket" required="required" class="form-control col-md-7 col-xs-12">
                                        @foreach(config('leads.buckets') as $key => $bucket)
                                            <option value="{{ $key }}" {{ $lead->bucket == $key ? 'selected="selected"' : '' }}>{{ $bucket }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="priority">
                                    Priority <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <select id="priority" name="priority" required="required" class="form-control col-md-7 col-xs-12">
                                        @foreach(config('leads.priorities') as $key => $priority)
                                            <option value="{{ $key }}" {{ $lead->priority == $key ? 'selected="selected"' : '' }}>{{ $priority }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tags</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <autocomplete-tags :initial-tags="{{ json_encode($lead->tags()->get()->toArray()) }}"></autocomplete-tags>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="priority">Note</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea class="form-control" name="lead_notes" cols="30" rows="5">{{ $lead->lead_notes }}</textarea>
                                </div>
                            </div>

                            <div class="ln_solid"></div>

                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-success">Update</button>
                                    <delete-button
                                        :data="{{ $lead }}"
                                        message="Are you sure you want to delete this lead?"
                                        class="pull-right">
                                    </delete-button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection