routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Cargas routes
 */
require('routes/routes.cargas.php');



/**
 * Service request public routes
 */
Route::get('/request', 'AppointmentsController@getServiceRequest');
Route::post('/request', 'AppointmentsController@postServiceRequest');
Route::post('/request/verify-phone', 'AppointmentsController@verifyPhone');

/*
 * Contracts public routes - these are the old contract routes
 */
//Route::get('contracts/{id}/sign/{hash}', 'ContractsController@signContractLink')->name('contracts.sign');
//Route::get('contracts/{id}/download/{hash}', 'ContractsController@downloadContractLink');
//Route::put('contracts/sign/email/client', 'ContractsController@signEmailClient');
//Route::get('contracts/thankyou', function() {
//	return view('contracts.thankyou');
//})->name('contracts.thankyou');

/*
 * Agreements public routes
 */
Route::get('agreements/{id}/sign/{hash}', 'AgreementsController@signAgreementLink')->name('agreements.sign');
Route::get('agreements/{id}/download/{hash}', 'AgreementsController@downloadAgreementLink');
Route::put('agreements/sign/email/client', 'AgreementsController@signEmailClient');
Route::get('agreements/thankyou', function() {
    return view('agreements.thankyou');
})->name('agreements.thankyou');

/*
 * User routes
 */
Route::middleware(['user'])->group(function () {
	Route::get('/', 'HomeController@index');
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::get('estimates/active', 'EstimatesController@active')->name('estimates.active');
    Route::get('estimates/expired', 'EstimatesController@expired')->name('estimates.expired');
	Route::resource('estimates', 'EstimatesController');
    Route::patch('/estimates/update/column/{item}', 'EstimatesController@updateByColumn');
    Route::get('estimates/{id}/pdf', 'EstimatesController@generatePdf');
    Route::post('estimates/email', 'EstimatesController@sendEstimatePDFByEmail');

    // Agreements
    Route::get('agreements', 'AgreementsController@index')->name('agreements.index');
    Route::get('agreements/create/{base?}', 'AgreementsController@create')->name('agreements.create');
    Route::post('agreements/initiate', 'AgreementsController@initiate')->name('agreements.initiate');
    Route::get('agreements/prepare', 'AgreementsController@prepare')->name('agreements.getPrepare');
    Route::post('agreements/prepare', 'AgreementsController@prepare')->name('agreements.prepare');
    Route::post('agreements/services', 'AgreementsController@services')->name('agreements.services');
    Route::get('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/filled/client', 'AgreementsController@showFilledAgreementToClient')->name('agreements.show.client');
    Route::get('agreements/filled/employee', 'AgreementsController@showFilledAgreementToEmployee')->name('agreements.show.employee');
    Route::post('agreements/sign/client', 'AgreementsController@signNowClient');
    Route::post('agreements/sign/employee', 'AgreementsController@signNowEmployee');
    Route::get('agreements/store', 'AgreementsController@store');
    Route::get('agreements/{id}/download', 'AgreementsController@downloadAgreementPDF');
    Route::post('agreements/sign/email', 'AgreementsController@sendAgreementViaEmail');
    Route::post('agreements/resend', 'AgreementsController@resendAgreementLink');
    Route::put('agreements/sign/email/employee', 'AgreementsController@signEmailEmployee');
    Route::get('agreements/pending', 'AgreementsController@getPendingAgreements')->name('agreements.pending');
    Route::get('agreements/signed', 'AgreementsController@getSignedAgreements')->name('agreements.signed');
    Route::get('agreements/{agreement}/', 'AgreementsController@show');
    Route::delete('agreements/{agreement}', 'AgreementsController@destroy');

    // Create contract from estimates, contacts, addresses and leads
    // These are the old routes for contracts.
//	Route::get('estimates/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('estimates.create.contract');
//	Route::get('contacts/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('contacts.create.contract');
//	Route::get('addresses/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('addresses.create.contract');
//	Route::get('leads/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('leads.create.contract');

//  Route::resource('contracts', 'ContractsController')->only(['index']);
//  Route::post('contracts/services', 'ContractsController@configureServices');
//  Route::post('contracts/filled/client', 'ContractsController@showFilledContractToClient');
//  Route::post('contracts/sign/client', 'ContractsController@signNowClient');
//  Route::get('contracts/filled/employee', 'ContractsController@showFilledContractToEmployee');
//  Route::post('contracts/sign/employee', 'ContractsController@signNowEmployee');
//  Route::get('contracts/store', 'ContractsController@store');
//  Route::get('contracts/{id}/download', 'ContractsController@downloadContractPDF');
//	Route::post('contracts/sign/email', 'ContractsController@sendContractViaEmail');
//	Route::post('contracts/resend', 'ContractsController@resendContractLink');
//  Route::put('contracts/sign/email/employee', 'ContractsController@signEmailEmployee');
//  Route::get('contracts/pending', 'ContractsController@getPendingContracts')->name('contracts.pending');
//  Route::get('contracts/signed', 'ContractsController@getSignedContracts')->name('contracts.signed');
//	Route::get('contracts/migrate', 'ContractsController@migrate')->name('contracts.migrate');
//	Route::get('contracts/{contract}/', 'ContractsController@show');
//	Route::delete('contracts/{contract}', 'ContractsController@destroy');

    Route::resource('lineitems', 'EstimateItemsController');
    Route::patch('/lineitems/update/column/{item}', 'EstimateItemsController@updateByColumn');

    Route::resource('jobitems', 'JobItemsController');

    Route::resource('contacts', 'ContactsController');
    Route::get('/contacts/search/{query}', 'ContactsController@search');

    Route::resource('addresses', 'AddressesController');
    Route::get('/addresses/search/{string}', 'AddressesController@search');

	Route::resource('users', 'UsersController');
	Route::post('/users/{user}/avatar', 'UsersController@updateAvatar');
	Route::post('/users/{user}/change-password', 'UsersController@changePassword');
	Route::get('/users/search/{string}', 'UsersController@search');
	Route::post('/users/roles', 'UsersController@roles')->name('users.roles');
	Route::post('/users/{user}/signature', 'SignaturesController@store')->name('users.signature');
	Route::patch('/users/{user}/signature', 'SignaturesController@update');
	Route::delete('/users/{user}/signature', 'SignaturesController@destroy');
	Route::get('/users/{user}/unread-notifications', 'UsersController@getAllUnreadNotifications');
	Route::post('/users/{user}/read-notification', 'UsersController@markNotificationAsRead');
	Route::post('/users/{user}/read-all-notifications', 'UsersController@markAllNotificationsAsRead');
	Route::post('/users/{user}/send-message', 'MessagesController@send');
	Route::post('/users/send-message', 'MessagesController@send');
	Route::get('/messages/{message}', 'MessagesController@show');
	Route::delete('/messages/{message}', 'MessagesController@destroy');
	Route::patch('/messages/{message}/mark-as-read', 'MessagesController@markMessageAsRead');

	Route::resource('roles', 'RolesController');
	Route::resource('permissions', 'PermissionsController');

	Route::resource('appointments', 'AppointmentsController');
	Route::get('requests', 'AppointmentsController@getAllServiceRequests')->name('appointments.requests');
	Route::post('appointments/{appointment}/calendar-invite', 'AppointmentsController@calendarInvite');

	Route::resource('leads', 'LeadsController');
	Route::post('leads/{lead}/add-activity', 'LeadsController@addActivity');
	Route::post('leads/{lead}/assign/{user}', 'LeadsController@assign');

	Route::resource('notes', 'NotesController');

	Route::get('tickets/tanks', 'TicketsController@getTanks');
	Route::get('tickets/open', 'TicketsController@getOpenTickets')->name('tickets.open');
	Route::get('tickets/submitted', 'TicketsController@getSubmittedTickets')->name('tickets.submitted');
	Route::get('tickets/cleared', 'TicketsController@getClearedTickets')->name('tickets.cleared');
	Route::get('tickets/closed', 'TicketsController@getClosedTickets')->name('tickets.closed');
	Route::get('tickets/get-customer-types', 'TicketsController@getCustomerTypes');
	Route::resource('tickets', 'TicketsController');
	Route::post('tickets/add', 'TicketsController@addTicket');
	Route::patch('tickets/{ticket}/add-items', 'TicketsController@addItems');
	Route::patch('tickets/{ticket}/change-status', 'TicketsController@changeStatus');
	Route::get('tickets/{ticket}/get-ticket-activity', 'TicketsController@getTicketActivity');

	Route::get('search', 'SearchController@search');

	Route::post('shared/directories', 'AttachmentsController@directories');
	Route::post('shared/files', 'AttachmentsController@files');
});

/*
 * Admin routes
 */
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
	Route::get('/emails/logs', 'EmailLogsController@index')->name('emails.logs');
	Route::delete('/emails/logs/{log}', 'EmailLogsController@destroy');
	Route::get('/filemanager', function() {

resources/views/template/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> {{ config('app.title') }}</title>

    <!-- Bootstrap -->
    <link href="{{ asset('/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ asset('vendors/nprogress/nprogress.css') }}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{ asset('vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
    <!-- Switchery -->
    <link href="{{ asset('vendors/switchery/dist/switchery.min.css') }}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{{ asset('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{{ asset('build/css/custom.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @yield('css')
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">

            <div class="col-md-3 left_col">
                @include('template.menu')
            </div>

            <!-- Vue app -->
            <div id="app">
                <!-- top navigation -->
                @include('template.nav')
                <!-- /top navigation -->

                <!-- page content -->
                <div>
                    @yield('content')
                    <flash message="{{ session('flash') }}"></flash>
                    <errors :initial-errors="{{ json_encode($errors->all()) }}"></errors>
                </div>
                <!-- /page content -->
                <message-send-modal></message-send-modal>
            </div>
            <!-- /Vue app -->

            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Copyright &copy; {{ \Carbon\Carbon::now()->format('Y') }} {{ config('app.name') }}. All rights reserved. Powered by <a href="{{ config('links.digitalhost.url') }}" target="_blank">{{ config('links.digitalhost.title') }}</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <!-- jQuery -->
    <script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('vendors/nprogress/nprogress.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('vendors/iCheck/icheck.min.js') }}"></script>
    <!-- Switchery -->
    <script src="{{ asset('vendors/switchery/dist/switchery.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('vendors/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('vendors/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('vendors/pdfmake/build/vfs_fonts.js') }}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('build/js/custom.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Scripts -->
    <script type="text/javascript">
        window.App = {!! json_encode([
            'csrfToken' => csrf_token(),
            'user' => auth()->user(),
            'signedIn' => Auth::check(),
            'permissions' => auth()->user()->permissions()->pluck('name')->toArray(),
            'paymentTerms' => config('dropdowns.payment_terms'),
            'expiresIn' => config('dropdowns.expires'),
        ]) !!};

        // order tables by last column
        // $(document).ready(function() {
        //     $('#datatable-responsive').DataTable().columns(-1).order('desc').draw().responsive.recalc();
        // });
    </script>

    <!-- Page specific scripts -->
    @yield('scripts')
</body>
</html>

resources/views/template/menu.blade.php
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="{{ route('dashboard')}}" class="site_title"><i class="fa fa-fire"></i> <span>{{ config('app.title') }}</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            <img src="{{ asset(auth()->user()->getAvatar()) }}" class="img-circle profile_img">
        </div>

        <div class="profile_info">
            <span>Welcome,</span>
            <h2>{{ auth()->user()->name }}</h2>
        </div>
    </div>
    <!-- /menu profile quick info -->
    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
                <li><a href="{{ route('dashboard') }}"><i class="fas fa-home"></i> Home</a></li>
                
                 <li>
                    <a><i class="fas fa-file-invoice-dollar"></i> Cargas <span class="fas fa-angle-down pull-right"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{ route('cargas.inventory') }}"><span class="fas fa-sort-alpha-down"></span> Inventory</a></li>
                        <li><a href="{{ route('cargas.customers') }}"><span class="fas fa-sort-alpha-down"></span> Customers</a></li>
                        
                    </ul>
                </li>


                <li>
                    <a><i class="fas fa-users"></i> CRM <span class="fas fa-angle-down pull-right"></span></a>
	                <ul class="nav child_menu">
		                <li><a href="{{ route('leads.index') }}"><span class="fas fa-headset"></span> Leads</a></li>
		                <li><a href="{{ route('contacts.index') }}"><span class="fas fa-address-book"></span> Contacts</a></li>
		                <li><a href="{{ route('addresses.index') }}"><span class="fas fa-map-marked-alt"></span> Addresses</a></li>
                        <li><a href="{{ route('appointments.requests') }}"><span class="fas fa-calendar-check"></span> Service Requests</a></li>
                        <li><a href="{{ route('appointments.index') }}"><span class="fas fa-calendar-check"></span> Appointments</a></li>
	                </ul>
                </li>

                <li>
                    <a><i class="fas fa-file-contract"></i> Agreements <span class="fas fa-angle-down pull-right"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{ route('agreements.index') }}"><span class="fas fa-sort-alpha-down"></span> All</a></li>
                        <li><a href="{{ route('agreements.signed') }}"><span class="fas fa-check"></span> Signed</a></li>
                        <li><a href="{{ route('agreements.pending') }}"><span class="fas fa-tasks"></span> Pending</a></li>
                    </ul>
                </li>

                <li>
                    <a><i class="fas fa-file-invoice-dollar"></i> Estimates <span class="fas fa-angle-down pull-right"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{{ route('estimates.index') }}"><span class="fas fa-sort-alpha-down"></span> All</a></li>
                        <li><a href="{{ route('estimates.active') }}"><span class="fas fa-hourglass-start"></span> Active</a></li>
                        <li><a href="{{ route('estimates.expired') }}"><span class="fas fa-hourglass-end"></span> Expired</a></li>
                    </ul>
                </li>
                               
                
                
                

                <li><a href="{{ route('tickets.index') }}"><i class="fas fa-clipboard-list"></i> Tickets</a></li>
            </ul>
        </div>

        @if(auth()->user()->hasRole('admin') || auth()->user()->isSuperAdmin)
            <div class="menu_section">
                <h3>Admin</h3>
                <ul class="nav side-menu">
                @can('read_roles')
                    <li>
                        <a><i class="fas fa-users"></i> Users <span class="fas fa-angle-down pull-right"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ route('users.index') }}">List</a></li>
                            <li><a href="{{ route('roles.index') }}">Roles</a></li>
                            <li><a href="{{ route('permissions.index') }}">Permissions</a></li>
                        </ul>
                    </li>
                @elsecan('read_users')
                    <li><a href="{{ route('users.index') }}"><i class="fas fa-users"></i> Users</a></li>
                @endcan
                	<li><a href="{{ route('filemanager.index') }}"><i class="fas fa-folder-open"></i> File Manager</a></li>
                	<li><a href="{{ route('jobitems.index') }}"><i class="fas fa-hand-holding-usd"></i> Job Items</a></li>
                    <li><a href="{{ route('emails.logs') }}"><i class="far fa-envelope"></i> Email Logs</a></li>
                </ul>
            </div>
        @endif
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>

        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>

        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>

        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>

resources/views/template/nav.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{ asset(auth()->user()->getAvatar()) }}" class="img-circle"><span class="hidden-xs">{{ auth()->user()->name }}</span>
                        <i class="fas fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ auth()->user()->path() }}"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="{{ route('logout') }}"
	                        onclick="event.preventDefault();
		                    document.getElementById('logout-form').submit();">
			                    <i class="fas fa-sign-out-alt pull-right"></i> Log Out</a>
			                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;"><input type="hidden" name="_token" value="{{ Session::token() }}"></form>
			            </li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown" v-if="false">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="far fa-envelope"></i>
                    </a>
                </li>

                <notifications :initial-user="{{ auth()->user() }}" v-cloak></notifications>
                
                <search></search>
            </ul>
        </nav>
    </div>
</div>