routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Cargas routes
 */
require('routes/routes.cargas.php');



/**
 * Service request public routes
 */
Route::get('/request', 'AppointmentsController@getServiceRequest');
Route::post('/request', 'AppointmentsController@postServiceRequest');
Route::post('/request/verify-phone', 'AppointmentsController@verifyPhone');

/*
 * Contracts public routes - these are the old contract routes
 */
//Route::get('contracts/{id}/sign/{hash}', 'ContractsController@signContractLink')->name('contracts.sign');
//Route::get('contracts/{id}/download/{hash}', 'ContractsController@downloadContractLink');
//Route::put('contracts/sign/email/client', 'ContractsController@signEmailClient');
//Route::get('contracts/thankyou', function() {
//	return view('contracts.thankyou');
//})->name('contracts.thankyou');

/*
 * Agreements public routes
 */
Route::get('agreements/{id}/sign/{hash}', 'AgreementsController@signAgreementLink')->name('agreements.sign');
Route::get('agreements/{id}/download/{hash}', 'AgreementsController@downloadAgreementLink');
Route::put('agreements/sign/email/client', 'AgreementsController@signEmailClient');
Route::get('agreements/thankyou', function() {
    return view('agreements.thankyou');
})->name('agreements.thankyou');

/*
 * User routes
 */
Route::middleware(['user'])->group(function () {
	Route::get('/', 'HomeController@index');
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');

    Route::get('estimates/active', 'EstimatesController@active')->name('estimates.active');
    Route::get('estimates/expired', 'EstimatesController@expired')->name('estimates.expired');
	Route::resource('estimates', 'EstimatesController');
    Route::patch('/estimates/update/column/{item}', 'EstimatesController@updateByColumn');
    Route::get('estimates/{id}/pdf', 'EstimatesController@generatePdf');
    Route::post('estimates/email', 'EstimatesController@sendEstimatePDFByEmail');

    // Agreements
    Route::get('agreements', 'AgreementsController@index')->name('agreements.index');
    Route::get('agreements/create/{base?}', 'AgreementsController@create')->name('agreements.create');
    Route::post('agreements/initiate', 'AgreementsController@initiate')->name('agreements.initiate');
    Route::get('agreements/prepare', 'AgreementsController@prepare')->name('agreements.getPrepare');
    Route::post('agreements/prepare', 'AgreementsController@prepare')->name('agreements.prepare');
    Route::post('agreements/services', 'AgreementsController@services')->name('agreements.services');
    Route::get('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/configuration', 'AgreementsController@configuration')->name('agreements.configuration');
    Route::post('agreements/filled/client', 'AgreementsController@showFilledAgreementToClient')->name('agreements.show.client');
    Route::get('agreements/filled/employee', 'AgreementsController@showFilledAgreementToEmployee')->name('agreements.show.employee');
    Route::post('agreements/sign/client', 'AgreementsController@signNowClient');
    Route::post('agreements/sign/employee', 'AgreementsController@signNowEmployee');
    Route::get('agreements/store', 'AgreementsController@store');
    Route::get('agreements/{id}/download', 'AgreementsController@downloadAgreementPDF');
    Route::post('agreements/sign/email', 'AgreementsController@sendAgreementViaEmail');
    Route::post('agreements/resend', 'AgreementsController@resendAgreementLink');
    Route::put('agreements/sign/email/employee', 'AgreementsController@signEmailEmployee');
    Route::get('agreements/pending', 'AgreementsController@getPendingAgreements')->name('agreements.pending');
    Route::get('agreements/signed', 'AgreementsController@getSignedAgreements')->name('agreements.signed');
    Route::get('agreements/{agreement}/', 'AgreementsController@show');
    Route::delete('agreements/{agreement}', 'AgreementsController@destroy');

    // Create contract from estimates, contacts, addresses and leads
    // These are the old routes for contracts.
//	Route::get('estimates/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('estimates.create.contract');
//	Route::get('contacts/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('contacts.create.contract');
//	Route::get('addresses/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('addresses.create.contract');
//	Route::get('leads/{id}/contract/data/{base?}', 'ContractsController@selectBase')->name('leads.create.contract');

//  Route::resource('contracts', 'ContractsController')->only(['index']);
//  Route::post('contracts/services', 'ContractsController@configureServices');
//  Route::post('contracts/filled/client', 'ContractsController@showFilledContractToClient');
//  Route::post('contracts/sign/client', 'ContractsController@signNowClient');
//  Route::get('contracts/filled/employee', 'ContractsController@showFilledContractToEmployee');
//  Route::post('contracts/sign/employee', 'ContractsController@signNowEmployee');
//  Route::get('contracts/store', 'ContractsController@store');
//  Route::get('contracts/{id}/download', 'ContractsController@downloadContractPDF');
//	Route::post('contracts/sign/email', 'ContractsController@sendContractViaEmail');
//	Route::post('contracts/resend', 'ContractsController@resendContractLink');
//  Route::put('contracts/sign/email/employee', 'ContractsController@signEmailEmployee');
//  Route::get('contracts/pending', 'ContractsController@getPendingContracts')->name('contracts.pending');
//  Route::get('contracts/signed', 'ContractsController@getSignedContracts')->name('contracts.signed');
//	Route::get('contracts/migrate', 'ContractsController@migrate')->name('contracts.migrate');
//	Route::get('contracts/{contract}/', 'ContractsController@show');
//	Route::delete('contracts/{contract}', 'ContractsController@destroy');

    Route::resource('lineitems', 'EstimateItemsController');
    Route::patch('/lineitems/update/column/{item}', 'EstimateItemsController@updateByColumn');

    Route::resource('jobitems', 'JobItemsController');

    Route::resource('contacts', 'ContactsController');
    Route::get('/contacts/search/{query}', 'ContactsController@search');

    Route::resource('addresses', 'AddressesController');
    Route::get('/addresses/search/{string}', 'AddressesController@search');

	Route::resource('users', 'UsersController');
	Route::post('/users/{user}/avatar', 'UsersController@updateAvatar');
	Route::post('/users/{user}/change-password', 'UsersController@changePassword');
	Route::get('/users/search/{string}', 'UsersController@search');
	Route::post('/users/roles', 'UsersController@roles')->name('users.roles');
	Route::post('/users/{user}/signature', 'SignaturesController@store')->name('users.signature');
	Route::patch('/users/{user}/signature', 'SignaturesController@update');
	Route::delete('/users/{user}/signature', 'SignaturesController@destroy');
	Route::get('/users/{user}/unread-notifications', 'UsersController@getAllUnreadNotifications');
	Route::post('/users/{user}/read-notification', 'UsersController@markNotificationAsRead');
	Route::post('/users/{user}/read-all-notifications', 'UsersController@markAllNotificationsAsRead');
	Route::post('/users/{user}/send-message', 'MessagesController@send');
	Route::post('/users/send-message', 'MessagesController@send');
	Route::get('/messages/{message}', 'MessagesController@show');
	Route::delete('/messages/{message}', 'MessagesController@destroy');
	Route::patch('/messages/{message}/mark-as-read', 'MessagesController@markMessageAsRead');

	Route::resource('roles', 'RolesController');
	Route::resource('permissions', 'PermissionsController');

	Route::resource('appointments', 'AppointmentsController');
	Route::get('requests', 'AppointmentsController@getAllServiceRequests')->name('appointments.requests');
	Route::post('appointments/{appointment}/calendar-invite', 'AppointmentsController@calendarInvite');

	Route::resource('leads', 'LeadsController');
	Route::post('leads/{lead}/add-activity', 'LeadsController@addActivity');
	Route::post('leads/{lead}/assign/{user}', 'LeadsController@assign');

	Route::resource('notes', 'NotesController');

	Route::get('tickets/tanks', 'TicketsController@getTanks');
	Route::get('tickets/open', 'TicketsController@getOpenTickets')->name('tickets.open');
	Route::get('tickets/submitted', 'TicketsController@getSubmittedTickets')->name('tickets.submitted');
	Route::get('tickets/cleared', 'TicketsController@getClearedTickets')->name('tickets.cleared');
	Route::get('tickets/closed', 'TicketsController@getClosedTickets')->name('tickets.closed');
	Route::get('tickets/get-customer-types', 'TicketsController@getCustomerTypes');
	Route::resource('tickets', 'TicketsController');
	Route::post('tickets/add', 'TicketsController@addTicket');
	Route::patch('tickets/{ticket}/add-items', 'TicketsController@addItems');
	Route::patch('tickets/{ticket}/change-status', 'TicketsController@changeStatus');
	Route::get('tickets/{ticket}/get-ticket-activity', 'TicketsController@getTicketActivity');

	Route::get('search', 'SearchController@search');

	Route::post('shared/directories', 'AttachmentsController@directories');
	Route::post('shared/files', 'AttachmentsController@files');
});

/*
 * Admin routes
 */
Route::group(['prefix' => 'admin',  'middleware' => 'admin'], function() {
	Route::get('/emails/logs', 'EmailLogsController@index')->name('emails.logs');
	Route::delete('/emails/logs/{log}', 'EmailLogsController@destroy');
	Route::get('/filemanager', function() {
		return view('filemanager.index');
	})->name('filemanager.index');
});

Auth::routes();

/*
 * API Requests
 */

app/Http/Controllers/AddressesController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Http\Requests\AddressFormRequest;
use Illuminate\Http\Request;

class AddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('read_addresses');

        $addresses = Address::latest()->get();

        return view('addresses.list', compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('create_addresses');

        return view('addresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(AddressFormRequest $request)
    {
        $this->authorize('create_addresses');

        $address = Address::create([
            'contact_id' => $request->contact_id,
            'street_address' => $request->street_address,
            'suite_no' => $request->suite_no,
            'city' => $request->city,
            'state' => $request->state,
            'zip' => $request->zip,
        ]);

        if (request()->expectsJson()) {
            return $address->fresh();
        }

        return redirect('/addresses')
            ->with('flash', 'A new address has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Address $address
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Address $address)
    {
        $this->authorize('read_addresses');

        return view('addresses.show', compact('address'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Address $address
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Address $address)
    {
        $this->authorize('update_addresses');

        return view('addresses.edit', compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Address $address
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(AddressFormRequest $request, Address $address)
    {
        $this->authorize('update_addresses');

        $address->update([
            'contact_id' => $request->contact_id,
            'street_address' => $request->street_address,
            'suite_no' => $request->suite_no,
            'city' => $request->city,
            'state' => $request->state,
            'zip' => $request->zip,
        ]);

        if (request()->expectsJson()) {
            return $address->fresh();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Address $address
     * @return array
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Address $address)
    {
        $this->authorize('delete_addresses');

        $address->delete();

        return [
            'redirect' => route('addresses.index'),
            'message' => 'The address was deleted!'
        ];
    }

    /**
     * Search addresses by street address or contact first and last name.
     *
     * @param string $string
     * @return \Illuminate\Http\JsonResponse
     */
    public function search($string)
    {
        $addresses = Address::where('street_address', 'LIKE', '%' . $string . '%')
            ->orWhere('suite_no', 'LIKE', '%' . $string . '%')
            ->orWhereHas('contact', function ($query) use ($string) {
                $query->where(\DB::raw('concat(first_name," ",last_name)') , 'LIKE' , '%' . $string . '%');
            })->take(5)->get();

        return response()->json($addresses);
    }
}

resources/views/addresses/create.blade.php
@extends('template.main')

@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Add New Address</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Form</h2>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <form id="contact-form" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{{ route('addresses.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contact_id">
                                Contact Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <autocomplete-contact></autocomplete-contact>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="street_address">
                                Street Address <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="street_address" name="street_address" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="city">
                                City <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="city" name="city" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="state">
                                State <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="state" name="state" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="zip">
                                Zip Code <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="zip" name="zip" required="required" class="form-control col-md-7 col-xs-12">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="notes">
                                Notes <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="notes" name="notes" class="form-control"></textarea>
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button class="btn btn-primary" type="reset">Reset</button>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/addresses/edit.blade.php
@extends('template.main')

@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Update Address</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <update-address :initial-address="{{ $address }}"></update-address>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Form</h2>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <form id="contact-form" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{{ $address->path() }}">
                        {!! method_field('patch') !!}
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contact_id">
                                Contact Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="contact_id" name="contact_id" value="{{ $address->contact->fullName }}" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="street_address">
                                Street Address <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="street_address" name="street_address" value="{{ $address->street_address }}" required="required" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="street_address">
                                Suite #
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="street_address" name="suite_no" value="{{ $address->suite_no }}" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="city">
                                City <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="city" name="city" value="{{ $address->city }}" required="required" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="state">
                                State <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="state" name="state" value="{{ $address->state }}" required="required" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="zip">
                                Zip Code <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="zip" name="zip" value="{{ $address->zip }}" required="required" class="form-control col-md-7 col-xs-12" disabled="disabled">
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a class="btn btn-success" data-toggle="modal" data-target="#updateAddress">Edit this address</a>
                                @can('delete_addresses')
                                    <delete-button
                                        :data="{{ $address }}"
                                        message="Are you sure you want to delete this address"
                                        class="pull-right">
                                    </delete-button>
                                @endcan
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/addresses/list.blade.php
@extends('template.main')

@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Addresses</h3>
            </div>

        @can('create_addresses')
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search" align="right">
                    <div class="input-group">
                        <a data-toggle="modal" data-target="#widget-modal" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Add New</a>
                    </div>
                </div>
            </div>
        @endcan
        </div>

        <widget-modal></widget-modal>

        <div class="clearfix"></div>

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Addresses List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    <p class="text-muted font-13 m-b-30">This is the description for addresses listing</p>
                </div>

                <addresses-list :initial-addresses="{{ $addresses }}"></addresses-list>
            </div>
        </div>
    </div>
</div>
@endsection